export const SAVE_CUSTOMER_REQUEST = 'SAVE_CUSTOMER_REQUEST';
export const SAVE_CUSTOMER_SUCCESS = 'SAVE_CUSTOMER_SUCCESS';
export const SAVE_CUSTOMER_FAILURE = 'SAVE_CUSTOMER_FAILURE';

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE';

export const FIND_CUSTOMER_REQUEST = 'FIND_CUSTOMER_REQUEST';
export const FIND_CUSTOMER_SUCCESS = 'FIND_CUSTOMER_SUCCESS';
export const FIND_CUSTOMER_FAILURE = 'FIND_CUSTOMER_FAILURE';

export const FIND_CUSTOMERS_REQUEST = 'FIND_CUSTOMERS_REQUEST';
export const FIND_CUSTOMERS_SUCCESS = 'FIND_CUSTOMERS_SUCCESS';
export const FIND_CUSTOMERS_FAILURE = 'FIND_CUSTOMERS_FAILURE';
